### ISSUE TITLE
google images scraper not working

### ISSUE THREAD

**Issue by guillemontecinos** [montoyamoraga/scrapers#6]
Today I ran scraper-google-images on:

* macOS Sierra 10.12.6
* Python 3.7.2
* Homebrew 2.0.2
* pip 19.0.3

And received the following error message:

```
Traceback (most recent call last):
  File "script.py", line 227, in <module>
    scrape(scrapeSubject)
  File "script.py", line 114, in scrape
    scrollUpDown(driver)
  File "script.py", line 201, in scrollUpDown
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
  File "/Users/guillermo/Documents/Github/scrapers/scraper-google-images/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/Users/guillermo/Documents/Github/scrapers/scraper-google-images/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/guillermo/Documents/Github/scrapers/scraper-google-images/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=72.0.3626.109)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
```

**Comment by periode** [comment]
Hey!

I had a similar issue. In my case, it was because of a version mismatch between chromedriver and chrome. Fixed it by upgrading to [chromedriver v2.36](https://chromedriver.storage.googleapis.com/index.html?path=2.36/).
